### ISSUE TITLE
빈 노트 작성시 그룹페이지로 redirect가 아닌 exception 페이지로 넘어감

### ISSUE THREAD

**Issue by alpha2015** [NHNNEXT/2015-01-WEB-GUINNESS#113]

**Comment by HelloMocca** [comment]
note를 작성하지 않은 채 "작성"버튼을 누르게 되면 일지가 작성되지 않았다는 경고가 뜨도록 변경.
Javascript로 유효성 체크를 하며 이를 우회하여 서버에 요청할시 exception 페이지로 넘어가도록 함.
