### ISSUE TITLE
일지 작성 >> 에디터 구현

### ISSUE THREAD

**Issue by hwiba** [NHNNEXT/2015-01-WEB-GUINNESS#117]
"1. 마크다운으로 DB에 저장
2. 민트마크 추가-어노테이션(!!!~!!!, ???~???)
3. 멀티마크다운 문법 적용"

**Comment by ybin0823** [comment]
스페이스 2번 혹은 2번 enter로 줄바꿈이 되는게 불편한 감이 있습니다.
리스트, 코드 문법 구현 우선순위를 높여서 개발이 되면 좋을 것 같습니다.
