### ISSUE TITLE
mysql 5.5 version에서 invalid default value current_timestamp 에러 발생함. 

### ISSUE THREAD

**Issue by javajigi** [NHNNEXT/2015-01-WEB-GUINNESS#71]
http://stackoverflow.com/questions/9005766/invalid-default-value-for-dateadded

이 링크에도 있듯이 datetime type에서 current_timestamp을 사용할 경우 에러 발생함.
mysql의 하위 호환성을 어디까지로 둘 것인가?

mysql 5.5에서도 동작하도록 해주면 안될까나?

**Comment by HelloMocca** [comment]
저희도 데모서버 구성하는 단계에서 mysql을 5.5로 설치했더니 그런 문제를 발견할 수 있었습니다...
해당 디폴트를 사용안하거나 하위버전 호환용 dbSetting.sql 을 동시에 배포해야 할 것 같습니다.
