### ISSUE TITLE
삭제한 그룹(존재하지 않는 그룹)의 ID URL로 접속이 가능 오류

### ISSUE THREAD

**Issue by alpha2015** [NHNNEXT/2015-01-WEB-GUINNESS#74]
그룹 삭제 전 해당 그룹 노트 URL을 삭제 후 접속시도시 접속이 됨.

삭제 된 ID 뿐만 아니라 아예 존재하지 않았던 노트페이지도 접속 가능
EX) http://localhost:8080/g/TEsTid

**Comment by ybin0823** [comment]
그룹 삭제할 때 세션에 남아 있어서 그런 듯. 세션도 같이 지워주면 해결 가능할 것으로 예상됩니다.
