### ISSUE TITLE
modal의 중복제거

### ISSUE THREAD

**Issue by ybin0823** [NHNNEXT/2015-01-WEB-GUINNESS#87]
현재 group, note생성시와 note를 조회할 때, alert창을 띄울 때 사용하는 modal에 중복이 많다. 이를 해결할 방법을 고민해 보자.

**Comment by HelloMocca** [comment]
guinness.util.modal() 을 이용하여

modal-cover
  modal-container
     modal-header
     modal-body

구조의 기본 modal을 생성하도록 하고 modal-body는 각각의 template을 받아 appendChild 하도록 구현함
